"""c

Revision ID: 306b04a0de4a
Revises: 
Create Date: 2026-06-02 08:58:06.525689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306b04a0de4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_email'), 'resume', ['email'], unique=False)
    op.create_index(op.f('ix_resume_experience'), 'resume', ['experience'], unique=False)
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    op.create_index(op.f('ix_resume_name'), 'resume', ['name'], unique=False)
    op.create_index(op.f('ix_resume_phone'), 'resume', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_phone'), table_name='resume')
    op.drop_index(op.f('ix_resume_name'), table_name='resume')
    op.drop_index(op.f('ix_resume_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_experience'), table_name='resume')
    op.drop_index(op.f('ix_resume_email'), table_name='resume')
    op.drop_table('resume')
    # ### end Alembic commands ###
