"""create jobs table

Revision ID: d38d157e47e2
Revises: e3b8f3e96da1
Create Date: 2026-06-08 00:17:05.233184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38d157e47e2'
down_revision: Union[str, Sequence[str], None] = 'e3b8f3e96da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Jobs_create_at'), table_name='Jobs')
    op.drop_index(op.f('ix_Jobs_id'), table_name='Jobs')
    op.drop_index(op.f('ix_Jobs_title'), table_name='Jobs')
    op.drop_table('Jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('create_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Jobs_title'), 'Jobs', ['title'], unique=1)
    op.create_index(op.f('ix_Jobs_id'), 'Jobs', ['id'], unique=1)
    op.create_index(op.f('ix_Jobs_create_at'), 'Jobs', ['create_at'], unique=False)
    # ### end Alembic commands ###
